[package]
name = "waffle0823/luau-typed-enum"
description = "A custom enum module for luau"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
